{{- if .Values.ingress.internal.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName.name }}-ing
  namespace: {{ .Values.appName.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ default "/" $.Values.ingress.internal.healthcheckPath | quote }}
  {{- end }}
spec:
  {{- with .Values.ingress.internal.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.internal.tls }}
  tls:
    {{- range .Values.ingress.internal.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.internal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ printf "%s-svc" $.Values.appName.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
