name: Test Secret Enabled

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hardcode JSON and evaluate
        run: |
          cat <<EOF > payload.json
          {
            "data":{
              "applicationName":"checkout",
              "environment":"dev",
              "env": {
                "JAVA_OPTS":"-Xms512m"
              },
              "secret": null
            }
          }
          EOF

          echo "===== Payload ====="
          cat payload.json

          # if env OR secret exists -> true else false
          if jq -e '.data.env != null or .data.secret != null' payload.json >/dev/null; then
            echo "SECRET_ENABLED=true" >> $GITHUB_ENV
          else
            echo "SECRET_ENABLED=false" >> $GITHUB_ENV
          fi

      - name: Show Result
        run: |
          echo "SECRET_ENABLED=$SECRET_ENABLED"
