name: master job
on:
  repository_dispatch:
    types: [jira-trigger]
permissions:
  issues: write   # 
  contents: write

jobs:
  setup-dependencies:
   needs: orchestrator
   runs-on: self-hosted
   steps:
     - name: Install required tools
       run: |
        echo "🔧 Installing dependencies..."

        sudo apt-get update

        # Install Docker
        if ! command -v docker &> /dev/null; then
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
        fi
        # Install Python & pip
        if ! command -v python3 &> /dev/null; then
          sudo apt-get install -y python3 python3-pip
        fi
        # Install Python packages
        pip3 install --upgrade pip
        pip3 install jinja2 pyyaml

        # Install Helm
        if ! command -v helm &> /dev/null; then
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        fi

        # Install envsubst
        if ! command -v envsubst &> /dev/null; then
          sudo apt-get install -y gettext
        fi

        # Install GitHub CLI
        if ! command -v gh &> /dev/null; then
          sudo apt-get install -y gh
        fi

        echo "✅ All dependencies installed"

     - name: Verify tools
       run: |
         docker --version
         helm version
         envsubst --version
         gh --version 
         python3 --version
         pip3 --version
         python3 -c "import jinja2, yaml; print('Python libs OK')"

  orchestrator:
    runs-on: ubuntu-latest

    steps:

    # =========================
    # 0. DEBUG 
    # =========================
    - name: Print Full Payload
      run: echo '${{ toJson(github.event.client_payload) }}'

    # =========================
    # 1. PARSE JSON
    # =========================
    - name: Set Variables from Payload
      run: |
        echo "APP_NAME=${{ github.event.client_payload.data.applicationName }}" >> $GITHUB_ENV
        echo "ENV=${{ github.event.client_payload.data.environment }}" >> $GITHUB_ENV
        echo "NAMESPACE=tapapps" >> $GITHUB_ENV
        echo "TIER=backend" >> $GITHUB_ENV

        echo "CPU_REQUEST=100m" >> $GITHUB_ENV
        echo "MEMORY_REQUEST=200Mi" >> $GITHUB_ENV
        echo "CPU_LIMIT=200m" >> $GITHUB_ENV
        echo "MEMORY_LIMIT=400Mi" >> $GITHUB_ENV
        echo "PORT=8080" >> $GITHUB_ENV
        echo "HEALTH_PATH=/health" >> $GITHUB_ENV

        echo "PUBLIC_INGRESS_ENABLED=${{ github.event.client_payload.data.dns.public }}" >> $GITHUB_ENV
        echo "PRIVATE_INGRESS_ENABLED=${{ github.event.client_payload.data.dns.private }}" >> $GITHUB_ENV

        echo "INGRESS_HOST=${{ github.event.client_payload.data.applicationName }}.${{ github.event.client_payload.data.environment }}.tap.company.aws" >> $GITHUB_ENV

        echo "INGRESS_PATH=/" >> $GITHUB_ENV
        echo "SECRET_ENABLED=true" >> $GITHUB_ENV
        echo "REPO_URL=${{ github.event.client_payload.data.repourl }}" >> $GITHUB_ENV"

    # =========================
    # 2. VALIDATION
    # =========================
    - name: Validate Inputs
      run: |
        if [ -z "$APP_NAME" ]; then
          echo "❌ applicationName missing"; exit 1;
        fi

    # =========================
    # 3. DNS STAGE
    # =========================
    - name: DNS Provisioning
      run: |
        echo "🌐 DNS Stage..."

        if [ "$DNS_PUBLIC" = "true" ]; then
          echo "Creating PUBLIC DNS for $APP-$ENV"
        fi

        if [ "$DNS_PRIVATE" = "true" ]; then
          echo "Creating PRIVATE DNS for $APP-$ENV"
        fi

    # =========================
    # 4. DATABASE STAGE
    # =========================
    - name: Database Setup
      run: |
        echo "🗄 Database Stage..."

        if [ "$POSTGRES" = "true" ]; then
          echo "Creating PostgreSQL DB"
        fi

        if [ "$MYSQL" = "true" ]; then
          echo "Creating MySQL DB"
        fi

    # =========================
    # 5. QUEUE STAGE
    # =========================
    - name: Queue Setup
      run: |
        echo "📩 Queue Stage..."

        if [ "$KAFKA" = "true" ]; then
          echo "Setting up Kafka"
        fi

        if [ "$SQS" = "true" ]; then
          echo "Setting up SQS"
        fi

    # =========================
    # 6. HELM STAGE
    # =========================
    - name: Checkout Target Branch
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Show Repo Info
      run: |
        pwd
        ls -la
    - name: Generate values file
      run: |
         envsubst < helmchart/temp.yaml > helmchart/env/${{ github.event.client_payload.data.environment }}/${{ github.event.client_payload.data.applicationName }}.yaml
    - name: Run Helm Template
      run: |
        helm template $APP_NAME helmchart \
           -f helmchart/env/$ENV/$APP_NAME.yaml
    - name: Git Commit & Push
      run: |
        BRANCH="onboard/${APP_NAME}-${ENV}-${GITHUB_RUN_ID}"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b $BRANCH
        git add helmchart/env/$ENV/$APP_NAME.yaml  
        git commit -m "Add onboarding config for $APP_NAME ($ENV)"
        git push origin $BRANCH
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        BRANCH="onboard/${APP_NAME}-${ENV}-${GITHUB_RUN_ID}"
        gh pr create \
          --title "Onboard $APP_NAME ($ENV)" \
          --body "Auto-generated onboarding config from Jira payload" \
          --base main \
          --head $BRANCH
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: farhanali67   # ✅ your username
          minimum-approvals: 1
          issue-title: "Review helmchart values "
          issue-body: "Approve to continue"
    # =========================
    # 7. JENKINS DSL CREATION
    # =========================
    - name: Set ENV variable
      run: |
        ENV_VALUE="${{ github.event.client_payload.data.environment }}"
        if [ "$ENV_VALUE" = "dev" ]; then
          ENV_VALUE="development"
        fi
        echo "ENV=$ENV_VALUE" >> $GITHUB_ENV
    
    - name: Trigger Jenkins Seed Job
      run: |
        curl -X POST "${{ secrets.JENKINS_URL }}/job/JenkinsDSL/job/automation-dsl-eks/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          --data-urlencode "JOB_NAME=$APP_NAME-$ENV-eks" \
          --data-urlencode "envName=$ENV" \
          --data-urlencode "REPO_URL=$REPO_URL" \
          --data-urlencode "BRANCH=refs/heads/$BRANCH" \
          --data-urlencode "CREDENTIALS_ID=Jenkins-github-connection" \
          --data-urlencode "SCRIPT_PATH=Jenkinsfile" -k 

    # =========================
    # 8. TRIGGER JENKINS JOB
    # =========================
    - name: Trigger Jenkins Job
      run: |
        echo "🚀 Triggering Jenkins Job..."

        curl -X POST "${{ secrets.JENKINS_URL }}/job/${APP}-eks-${ENV}/build" \
        --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"

    # =========================
    # 9. DONE
    # =========================
    - name: Complete
      run: |
        echo "✅ Platform orchestration completed for $APP in $ENV"
