name: master job
on:
  repository_dispatch:
    types: [jira-trigger]

permissions:
  contents: write

jobs:
  orchestrator:
    runs-on: ubuntu-latest

    steps:

    # =========================
    # 0. DEBUG (IMPORTANT)
    # =========================
    - name: Print Full Payload
      run: echo '${{ toJson(github.event.client_payload) }}'

    # =========================
    # 1. PARSE JSON
    # =========================
    - name: Set Variables from Payload
      run: |
        echo "APP_NAME=${{ github.event.client_payload.data.applicationName }}" >> $GITHUB_ENV
        echo "ENV=${{ github.event.client_payload.data.environment }}" >> $GITHUB_ENV
        echo "NAMESPACE=tapapps" >> $GITHUB_ENV
        echo "TIER=backend" >> $GITHUB_ENV

        echo "CPU_REQUEST=100m" >> $GITHUB_ENV
        echo "MEMORY_REQUEST=200Mi" >> $GITHUB_ENV
        echo "CPU_LIMIT=200m" >> $GITHUB_ENV
        echo "MEMORY_LIMIT=400Mi" >> $GITHUB_ENV
        echo "PORT=8080" >> $GITHUB_ENV
        echo "HEALTH_PATH=/health" >> $GITHUB_ENV

        echo "PUBLIC_INGRESS_ENABLED=${{ github.event.client_payload.data.dns.public }}" >> $GITHUB_ENV
        echo "PRIVATE_INGRESS_ENABLED=${{ github.event.client_payload.data.dns.private }}" >> $GITHUB_ENV

        echo "INGRESS_HOST=${{ github.event.client_payload.data.applicationName }}.${{ github.event.client_payload.data.environment }}.tap.company.aws" >> $GITHUB_ENV

        echo "INGRESS_PATH=/" >> $GITHUB_ENV

    # =========================
    # 2. VALIDATION
    # =========================
    - name: Validate Inputs
      run: |
        if [ -z "$APP_NAME" ]; then
          echo "❌ applicationName missing"; exit 1;
        fi

    # =========================
    # 3. DNS STAGE
    # =========================
    - name: DNS Provisioning
      run: |
        echo "🌐 DNS Stage..."

        if [ "$DNS_PUBLIC" = "true" ]; then
          echo "Creating PUBLIC DNS for $APP-$ENV"
        fi

        if [ "$DNS_PRIVATE" = "true" ]; then
          echo "Creating PRIVATE DNS for $APP-$ENV"
        fi

    # =========================
    # 4. DATABASE STAGE
    # =========================
    - name: Database Setup
      run: |
        echo "🗄 Database Stage..."

        if [ "$POSTGRES" = "true" ]; then
          echo "Creating PostgreSQL DB"
        fi

        if [ "$MYSQL" = "true" ]; then
          echo "Creating MySQL DB"
        fi

    # =========================
    # 5. QUEUE STAGE
    # =========================
    - name: Queue Setup
      run: |
        echo "📩 Queue Stage..."

        if [ "$KAFKA" = "true" ]; then
          echo "Setting up Kafka"
        fi

        if [ "$SQS" = "true" ]; then
          echo "Setting up SQS"
        fi

    # =========================
    # 6. HELM STAGE
    # =========================
    - name: Checkout Target Branch
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Show Repo Info
      run: |
        pwd
        ls -la
    - name: Generate values file
      run: |
         envsubst < helmchart/temp.yaml > helmchart/env/${{ github.event.client_payload.data.environment }}/${{ github.event.client_payload.data.applicationName }}.yaml
    - name: Run Helm Template
      run: |
        helm template $APP_NAME helmchart \
           -f helmchart/env/$ENV/$APP_NAME.yaml
    - name: Git Commit & Push
      run: |
        BRANCH="onboard/${APP_NAME}-${ENV}-${GITHUB_RUN_ID}"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b $BRANCH
        git add helmchart/env/$ENV/$APP_NAME.yaml  
        git commit -m "Add onboarding config for $APP_NAME ($ENV)"
        git push origin $BRANCH
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="onboard/${APP_NAME}-${ENV}-${GITHUB_RUN_ID}"
        gh pr create \
          --title "Onboard $APP_NAME ($ENV)" \
          --body "Auto-generated onboarding config from Jira payload" \
          --base main \
          --head $BRANCH_NAME
    # =========================
    # 7. JENKINS DSL CREATION
    # =========================
    - name: Create Jenkins DSL Job
      run: |
        echo "⚙️ Creating Jenkins DSL Job..."

        curl -X POST "${{ secrets.JENKINS_URL }}/generic-webhook-trigger/invoke?token=jira-trigger" \
        -H "Content-Type: application/json" \
        -d '{
          "applicationName": "'"$APP"'",
          "envName": "'"$ENV"'"
        }'

    # =========================
    # 8. TRIGGER JENKINS JOB
    # =========================
    - name: Trigger Jenkins Job
      run: |
        echo "🚀 Triggering Jenkins Job..."

        curl -X POST "${{ secrets.JENKINS_URL }}/job/${APP}-eks-${ENV}/build" \
        --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"

    # =========================
    # 9. DONE
    # =========================
    - name: Complete
      run: |
        echo "✅ Platform orchestration completed for $APP in $ENV"
